//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Activity
{
    public int ActivityID { get; set; }
    public string ActivityName { get; set; }
    public System.DateTime CreatedOn { get; set; }
    public string CreatedBy { get; set; }
    public string Speaker { get; set; }
    public string Location { get; set; }
    public string Message { get; set; }
}

public partial class Admin
{
    public int AdminID { get; set; }
    public int LicenceID { get; set; }
    public int AdminDetailsID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public System.DateTime DOB { get; set; }
}

public partial class AdminDetail
{
    public int AdminDetailsID { get; set; }
    public string Password { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string PostZipCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Email { get; set; }
    public string Permission { get; set; }
}

public partial class Announcement
{
    public int AnnouncementID { get; set; }
    public int BranchID { get; set; }
    public string AnnouncementType { get; set; }
    public string Sender { get; set; }
    public string Purpose { get; set; }
    public string Comment { get; set; }
}

public partial class AppointmentReview
{
    public int ID { get; set; }
    public int Memberid { get; set; }
    public int AppointeeID { get; set; }
    public int BranchID { get; set; }
    public string NewRole { get; set; }
    public string CurrentRole { get; set; }
    public int StartDate { get; set; }
    public int EndDate { get; set; }
    public Nullable<int> NumOfRoles { get; set; }
    public string Flag { get; set; }
    public string RoleStatus { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class AppointmentRole
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class Area
{
    public int ID { get; set; }
    public string Name { get; set; }
}

public partial class Asset
{
    public int AssetID { get; set; }
    public int BranchID { get; set; }
    public int Source { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string PurchasedBy { get; set; }
    public Nullable<decimal> Cost { get; set; }
    public string Location { get; set; }
}

public partial class AssignedBranch
{
    public int ID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public Nullable<int> MemberBranchID { get; set; }
    public Nullable<int> AssignedBranchID { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
}

public partial class Association
{
    public int AssociationId { get; set; }
    public string AssociationName { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
}

public partial class Attendance
{
    public int AttendanceID { get; set; }
    public int MemberID { get; set; }
    public int ActivityID { get; set; }
    public System.DateTime AttendanceDate { get; set; }
    public string ActivityName { get; set; }
    public Nullable<int> BranchID { get; set; }
}

public partial class AuditTrail
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public int DateLoggedIn { get; set; }
    public string TimeLoggedIn { get; set; }
    public string PageVisited { get; set; }
}

public partial class BankAccount
{
    public int ID { get; set; }
    public string Sortcode { get; set; }
    public string AccountNumber { get; set; }
    public int BranchID { get; set; }
    public string Description { get; set; }
    public string AccountType { get; set; }
}

public partial class BankTransaction
{
    public int ID { get; set; }
    public string ReferenceNumber { get; set; }
    public string PrimaryAccount { get; set; }
    public string TransactionType { get; set; }
    public string Details { get; set; }
    public int BranchID { get; set; }
    public string Paymode { get; set; }
    public string Date { get; set; }
    public decimal Amount { get; set; }
    public Nullable<decimal> VAT { get; set; }
    public string AnalysisAccount { get; set; }
    public string FurtherDetails { get; set; }
    public string CreatedOn { get; set; }
    public int MemberID { get; set; }
    public string AccountType { get; set; }
    public string IsReceipt { get; set; }
    public string ReceiptLocation { get; set; }
}

public partial class Book
{
    public int BookID { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    public string PublicationYear { get; set; }
    public string Publisher { get; set; }
    public int Quantity { get; set; }
    public Nullable<decimal> UnitCost { get; set; }
    public string ImagePath { get; set; }
}

public partial class Branch
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Telephone { get; set; }
    public string Website { get; set; }
    public string PresidingElder { get; set; }
    public string EmailAddress { get; set; }
    public Nullable<int> AreaID { get; set; }
    public Nullable<int> DistrictID { get; set; }
}

public partial class BranchAccount
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public string PrimaryAccount { get; set; }
    public string PrimarAccountSortCode { get; set; }
}

public partial class BranchDetail
{
    public int BranchID { get; set; }
    public int ChurchDetailsID { get; set; }
    public string Name { get; set; }
    public string AddressOne { get; set; }
    public string AddressTwo { get; set; }
    public string PostZipCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Website { get; set; }
}

public partial class BranchGrouping
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public string BranchGroupingType { get; set; }
    public string GroupingName { get; set; }
    public string BranchName { get; set; }
}

public partial class CellGroup
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public int MemberID { get; set; }
    public string Role { get; set; }
    public string Location { get; set; }
    public string Groupname { get; set; }
    public string Meetingday { get; set; }
    public string Meetingtime { get; set; }
    public string Datejoined { get; set; }
    public string ActiveStatus { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
}

public partial class ChurchDetail
{
    public int ChurchID { get; set; }
    public string ChurchName { get; set; }
    public string CharityNumber { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string Town { get; set; }
    public string Telephone { get; set; }
    public string WebAddress { get; set; }
    public string PostCode { get; set; }
}

public partial class ChurchGroup
{
    public int ChurchGroupID { get; set; }
    public string Name { get; set; }
    public System.DateTime DateCreated { get; set; }
    public string CreatedBy { get; set; }
    public string Comment { get; set; }
    public string GroupType { get; set; }
}

public partial class Client
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Logo { get; set; }
    public string Slogan { get; set; }
    public string Twitter { get; set; }
    public string Facebook { get; set; }
    public string Yahoo { get; set; }
    public string Instagram { get; set; }
    public string Hangout { get; set; }
    public string PanelCaption { get; set; }
    public string PanelTitle { get; set; }
    public string Theme { get; set; }
    public string Youtube { get; set; }
}

public partial class CommentTable
{
    public int CommentID { get; set; }
    public int CommentMemberID { get; set; }
    public int OccassionImageID { get; set; }
    public System.DateTime CommentDate { get; set; }
    public string Comment { get; set; }
}

public partial class Communication
{
    public int CommunicationID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime CommunicationDate { get; set; }
    public string CommunicationType { get; set; }
    public string CommunicationPurpose { get; set; }
    public string CommunicationOutcome { get; set; }
}

public partial class Configuration
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Value { get; set; }
}

public partial class Contribution
{
    public int ContributionID { get; set; }
    public int MemberID { get; set; }
    public string ContributionType { get; set; }
    public System.DateTime ContributionDate { get; set; }
    public decimal Amount { get; set; }
    public string Comment { get; set; }
}

public partial class ConventionAndConference
{
    public int ID { get; set; }
    public string name { get; set; }
    public string date { get; set; }
    public string speaker { get; set; }
    public string title { get; set; }
    public string malecount { get; set; }
    public string femalecount { get; set; }
    public string children { get; set; }
    public string spectacularevent { get; set; }
    public string specialOccurence { get; set; }
    public string soulsWon { get; set; }
    public string convertsWaterBaptised { get; set; }
    public string membersWaterBaptised { get; set; }
    public string holySpiritBaptised { get; set; }
    public string titheAndOffering { get; set; }
    public string otherOffering { get; set; }
    public string authorisedExpenditure { get; set; }
    public string generalAssessment { get; set; }
    public string certificationMinister { get; set; }
    public string officiatingMinister { get; set; }
}

public partial class Country
{
    public int ID { get; set; }
    public string CountryName { get; set; }
    public Nullable<bool> IsSelected { get; set; }
}

public partial class Country1
{
    public int CountryID { get; set; }
    public string EnglishName { get; set; }
    public string FrenchName { get; set; }
    public string LocalName { get; set; }
    public string Region { get; set; }
}

public partial class COVID_Temperature
{
    public int Id { get; set; }
    public int MemberID { get; set; }
    public decimal Temperature { get; set; }
    public Nullable<System.DateTime> DateTaken { get; set; }
}

public partial class Department
{
    public int DepartmentID { get; set; }
    public int MemberID { get; set; }
    public int GroupID { get; set; }
    public Nullable<System.DateTime> DateJoined { get; set; }
    public string Role { get; set; }
}

public partial class Dictionary
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Value { get; set; }
    public string PageName { get; set; }
}

public partial class Discipline
{
    public int DisciplineID { get; set; }
    public int BranchID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime FromDate { get; set; }
    public System.DateTime ToDate { get; set; }
    public string DisciplineType { get; set; }
    public string Comment { get; set; }
}

public partial class District
{
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Code { get; set; }
}

public partial class DistrictEvent
{
    public int DistrictEventsID { get; set; }
    public string SermonTitle { get; set; }
    public string EventSummary { get; set; }
    public string Location { get; set; }
    public string Time { get; set; }
    public string Date { get; set; }
    public Nullable<decimal> Offering { get; set; }
    public string SpectacularEvent { get; set; }
    public string OpeningPrayer { get; set; }
    public string ClosingPrayer { get; set; }
    public string EventTheme { get; set; }
    public string Comment { get; set; }
    public string InvitedGuests { get; set; }
    public Nullable<int> EldersCount { get; set; }
    public Nullable<int> DeaconsCount { get; set; }
    public int MaleCount { get; set; }
    public int FemaleCount { get; set; }
    public Nullable<int> ChildrenCount { get; set; }
    public Nullable<int> YouthCount { get; set; }
    public Nullable<int> AdultsCount { get; set; }
    public Nullable<int> DeaconessesCount { get; set; }
}

public partial class Donor
{
    public int DonorID { get; set; }
    public string DonorName { get; set; }
    public Nullable<System.DateTime> DonationDate { get; set; }
    public int BookID { get; set; }
}

public partial class Event
{
    public int EventsID { get; set; }
    public int BranchID { get; set; }
    public string Name { get; set; }
    public string EventDate { get; set; }
    public string Purpose { get; set; }
    public string Location { get; set; }
    public string GuestSpeakers { get; set; }
    public string PresidingOfficer { get; set; }
    public Nullable<int> MenCount { get; set; }
    public Nullable<int> WomenCount { get; set; }
    public Nullable<int> ChildrenCount { get; set; }
    public Nullable<decimal> TitherAndOffering { get; set; }
    public string Comment { get; set; }
    public Nullable<int> HolySpiritBaptised { get; set; }
    public Nullable<int> SoulsWon { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public string CreatedBy { get; set; }
}

public partial class Expenditure
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
    public decimal Amount { get; set; }
    public string ModeOfPayment { get; set; }
}

public partial class ExternalOrganization
{
    public int ExternalOrganisationID { get; set; }
    public string Name { get; set; }
    public string AddressOne { get; set; }
    public string AddressTwo { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string PostZipCode { get; set; }
    public string Telephone { get; set; }
    public string Website { get; set; }
}

public partial class Finance
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public string Paymode { get; set; }
    public int Date { get; set; }
    public decimal Amount { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
    public string Name { get; set; }
    public string AccountType { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class FinanceExpenditureItem
{
    public int ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string Source { get; set; }
}

public partial class FinanceExpenditureSource
{
    public System.Guid ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Source { get; set; }
}

public partial class FinanceFilter
{
    public int ID { get; set; }
    public string AccountType { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
    public string BranchID { get; set; }
    public int CreatedOn { get; set; }
    public string CreatedBy { get; set; }
}

public partial class FinanceIncomeItem
{
    public int ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string Source { get; set; }
}

public partial class FinanceIncomeSource
{
    public System.Guid ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Source { get; set; }
}

public partial class FinancePayMode
{
    public int ID { get; set; }
    public string Alias { get; set; }
    public string PayMode { get; set; }
}

public partial class FollowUpResponse
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public int ActivityID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string MemberNames { get; set; }
    public string Purpose { get; set; }
    public string Mode { get; set; }
    public string ContactDate { get; set; }
    public string Concerns { get; set; }
    public string IsMinisterInformed { get; set; }
    public string SupportOffered { get; set; }
    public string FollowedUpBy { get; set; }
    public string Comment { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string ActivityDate { get; set; }
    public string ActivityName { get; set; }
}

public partial class GiftAid
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string GIftAidId { get; set; }
    public int DateRegistered { get; set; }
    public string NINumber { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class Giving
{
    public int ID { get; set; }
    public int Memberid { get; set; }
    public int BranchID { get; set; }
    public string GIftAidId { get; set; }
    public int Date { get; set; }
    public string Fund { get; set; }
    public string Method { get; set; }
    public decimal Amount { get; set; }
    public decimal GiftAid { get; set; }
    public string Status { get; set; }
    public int EnvelopeCount { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class Income
{
    public int IncomeID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Type { get; set; }
    public decimal Amount { get; set; }
    public string ModeOfPayment { get; set; }
}

public partial class Interest
{
    public int InterestID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string Interest1 { get; set; }
    public int InterestRating { get; set; }
}

public partial class Inventory
{
    public int InventoryID { get; set; }
    public int BookID { get; set; }
    public int StockQuantity { get; set; }
}

public partial class Leadership
{
    public int LeadershipID { get; set; }
    public int MemberID { get; set; }
    public string Title { get; set; }
    public System.DateTime DateOfAppointment { get; set; }
    public System.DateTime EndOfAppointment { get; set; }
    public string Group { get; set; }
}

public partial class LeadershipChanx
{
    public int LeadershipChangesID { get; set; }
    public int BranchID { get; set; }
    public string OldRole { get; set; }
    public int OldBranchID { get; set; }
    public int NewBranchID { get; set; }
    public string NewRole { get; set; }
    public System.DateTime DateOfAppointment { get; set; }
    public string OfficiatingMinister { get; set; }
    public string Comment { get; set; }
    public int MemberID { get; set; }
}

public partial class Lending
{
    public int LendingID { get; set; }
    public int BookID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime LendDate { get; set; }
    public System.DateTime ExpectedDate { get; set; }
    public Nullable<System.DateTime> ReturnedDate { get; set; }
    public int Quantity { get; set; }
}

public partial class Letter
{
    public int LettersID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime DateSent { get; set; }
    public string TypeOfLetter { get; set; }
    public string PurposeOfLetters { get; set; }
}

public partial class LicenceLookUp
{
    public int LicenceLookUpID { get; set; }
    public string LincenseNumber { get; set; }
    public int ValidityPeriod { get; set; }
    public string LicenceType { get; set; }
    public int NumberOfUsers { get; set; }
}

public partial class License
{
    public int LicenseID { get; set; }
    public string LincenseNumber { get; set; }
    public System.DateTime LicenceStartDate { get; set; }
    public System.DateTime LicenceEndDate { get; set; }
    public int NumberOfUsers { get; set; }
}

public partial class LikeTable
{
    public int LikeTableID { get; set; }
    public int LikeMemberID { get; set; }
    public int OccassionImageID { get; set; }
    public System.DateTime LikeDate { get; set; }
}

public partial class local_activities_reminder
{
    public int Id { get; set; }
    public Nullable<int> MemberID { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string Message { get; set; }
    public string ActivityDate { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
}

public partial class LoginPermissionSet
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public int MemberID { get; set; }
    public string PagePermission { get; set; }
    public int DateCreated { get; set; }
    public string CreateBy { get; set; }
}

public partial class Mail
{
    public int MailID { get; set; }
    public int MemberID { get; set; }
    public int RecepientID { get; set; }
    public string Subject { get; set; }
    public string Body { get; set; }
    public Nullable<System.DateTime> DateSent { get; set; }
}

public partial class Meeting
{
    public int MeetingID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime MeetingDate { get; set; }
    public string MeetingType { get; set; }
    public string Chair { get; set; }
    public string Purpose { get; set; }
    public string Comment { get; set; }
}

public partial class Member
{
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public Nullable<int> DistrictID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string DOB { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string PostCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Comment { get; set; }
    public byte[] Picture { get; set; }
    public string Gender { get; set; }
    public string AgeCategory { get; set; }
    public byte[] AgeCategoryRep { get; set; }
    public string MembershipType { get; set; }
    public string RecordDate { get; set; }
    public string Password { get; set; }
    public string LoginType { get; set; }
    public string MemberTracking { get; set; }
    public string MaritalStatus { get; set; }
    public string Nationality { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string Profession { get; set; }
    public string Ethnicity { get; set; }
    public Nullable<int> PasswordDate { get; set; }
    public string AssignedBranchGroups { get; set; }
    public string BranchGroupings { get; set; }
    public Nullable<int> ThemeID { get; set; }
}

public partial class MemberAdmin
{
    public int MemberAdminID { get; set; }
    public string MemberID { get; set; }
    public string Password { get; set; }
    public string Permission { get; set; }
    public System.DateTime DateCreated { get; set; }
    public string CreatedBy { get; set; }
}

public partial class MemberAppointment
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string Role { get; set; }
    public int DateOfAppointment { get; set; }
    public int EndDateOfAppointment { get; set; }
    public int AlertNoticeDays { get; set; }
    public string AuthorisingOfficer { get; set; }
    public string Location { get; set; }
    public string Comment { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class MemberAppointmentRoleReview
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public int AppointmentID { get; set; }
    public Nullable<int> ReviewDate { get; set; }
    public string ReviewRole { get; set; }
    public string ReviewRoleFrom { get; set; }
    public string ReviewRoleTo { get; set; }
    public string ReviewRoleStrengths { get; set; }
    public string ReviewRoleWeakness { get; set; }
    public string ReviewRoleSupport { get; set; }
    public string ReviewComment { get; set; }
    public string RoleAction { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class MemberBaptism
{
    public int BaptismID { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string IsBornagain { get; set; }
    public string DateBornagain { get; set; }
    public string IsWaterBaptised { get; set; }
    public string OfficiatingMinister { get; set; }
    public string DateofBaptism { get; set; }
    public string PlaceOfBaptism { get; set; }
    public string CertificationDate { get; set; }
    public string RHFDate { get; set; }
    public string RHFOfficer { get; set; }
    public string IsHolySpiritBaptised { get; set; }
    public string HolySpiritBaptisedDate { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public int CreatedBy { get; set; }
    public string IsNewConvertWaterBaptised { get; set; }
    public string IsOldMemberHolySpiritBaptised { get; set; }
    public string IsCommunicant { get; set; }
    public string DateNewConvertWaterBaptised { get; set; }
    public string DateOldMemberHolySpiritBaptised { get; set; }
}

public partial class MemberGroup
{
    public int MemberGroupID { get; set; }
    public int ChurchGroupID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime DateJoined { get; set; }
    public string Role { get; set; }
}

public partial class MemberRelation
{
    public int RelationID { get; set; }
    public Nullable<int> BranchID { get; set; }
    public int MemberRelativeID { get; set; }
    public int MemberID { get; set; }
    public string RelationType { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class MemberRelative
{
    public string RelationType { get; set; }
    public int MemberRelativeID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string Branch_Name { get; set; }
    public string Branch_Country { get; set; }
    public int RelationID { get; set; }
}

public partial class MemberTransfer
{
    public int ID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public Nullable<int> DistrictID { get; set; }
    public Nullable<int> ToBranch { get; set; }
    public Nullable<int> FromBranch { get; set; }
    public string TransferType { get; set; }
    public string TransferDate { get; set; }
    public Nullable<int> MemberID { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
}

public partial class MemberUpdate
{
    public int Id { get; set; }
    public int BranchID { get; set; }
    public Nullable<int> Status { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public string HashKey { get; set; }
}

public partial class MonthlyReleaseAnnouncement
{
    public int MonthlyReleaseAnnouncementsId { get; set; }
    public System.DateTime Datefrom { get; set; }
    public System.DateTime ToDate { get; set; }
    public string Theme { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public string EventName { get; set; }
    public string Location { get; set; }
    public string Comment { get; set; }
    public string SpecialGuestSpeaker { get; set; }
}

public partial class MonthlyReleasePreaching
{
    public int MonthlyReleasePreachingID { get; set; }
    public string ServiceDate { get; set; }
    public string BranchName { get; set; }
    public string ServiceTimeFrom { get; set; }
    public string ServiceTimeTo { get; set; }
    public string ServiceName { get; set; }
    public string Speaker { get; set; }
}

public partial class National
{
    public int ID { get; set; }
    public string Name { get; set; }
}

public partial class NextOfKin
{
    public int Id { get; set; }
    public Nullable<int> MemberId { get; set; }
    public string FullName { get; set; }
    public string RelationType { get; set; }
    public string Address { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Email { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
}

public partial class OccassionImage
{
    public int OccassionImageID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime DateUploaded { get; set; }
    public byte[] MyImage { get; set; }
}

public partial class OfficeAppointment
{
    public int ID { get; set; }
    public int Memberid { get; set; }
    public int BranchID { get; set; }
    public string RoleId { get; set; }
    public int StartDate { get; set; }
    public int EndDate { get; set; }
    public string Location { get; set; }
    public string AuthorisingMinister { get; set; }
    public int DaysToExpiry { get; set; }
    public string Flag { get; set; }
    public int CreatedOn { get; set; }
    public int CreatedBy { get; set; }
}

public partial class PasswordReset
{
    public int ID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string PasswordHash { get; set; }
}

public partial class Phonebook
{
    public int Id { get; set; }
    public Nullable<int> BranchId { get; set; }
    public string Name { get; set; }
    public string TelephoneNumbers { get; set; }
}

public partial class PictureBox
{
    public int PicturboxID { get; set; }
    public int MemberID { get; set; }
    public byte[] Picture { get; set; }
    public string occassion { get; set; }
    public Nullable<System.DateTime> DateTaken { get; set; }
}

public partial class Planning
{
    public int ID { get; set; }
    public Nullable<int> FromDate { get; set; }
    public Nullable<int> ToDate { get; set; }
    public string StartTime { get; set; }
    public string EndTime { get; set; }
    public string ActivityName { get; set; }
    public string Description { get; set; }
    public string GuestSpeaker { get; set; }
    public string Location { get; set; }
}

public partial class Pledge
{
    public int Id { get; set; }
    public int MemberId { get; set; }
    public Nullable<decimal> Amount { get; set; }
}

public partial class PrayerRequest
{
    public int PrayerRequestID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime RequestDate { get; set; }
    public string PrayerCategory { get; set; }
    public string RequestDetails { get; set; }
}

public partial class Profession
{
    public int ProfessionID { get; set; }
    public int MemberID { get; set; }
    public string ProfessionName { get; set; }
    public string CompanyName { get; set; }
    public string IsCurrentRole { get; set; }
}

public partial class Programme
{
    public int ProgrammeID { get; set; }
    public string Name { get; set; }
    public Nullable<System.DateTime> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
    public int BranchID { get; set; }
}

public partial class ReportBug
{
    public int ReportBugID { get; set; }
    public string BugID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string UserName { get; set; }
    public string ChurchName { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Description { get; set; }
}

public partial class RepWeeklyServiceReport
{
    public int Id { get; set; }
    public string SelectBranchName { get; set; }
    public string MenCount { get; set; }
    public string WomenCount { get; set; }
    public string ChildrenCount { get; set; }
    public string SermonSpeaker { get; set; }
    public string BibleStudyTopic { get; set; }
    public string KeyInformation { get; set; }
    public string MidWeek { get; set; }
    public string MissionaryOffering { get; set; }
    public string NewMembers { get; set; }
    public string Other { get; set; }
    public string SermonSummary { get; set; }
    public string SermonTitle { get; set; }
    public string Specify { get; set; }
    public string Tithes { get; set; }
    public string AbsentTwoWeeks { get; set; }
    public string ActivityDate { get; set; }
}

public partial class SalvationAndBaptism
{
    public int SalvationAndBaptismID { get; set; }
    public int MemberID { get; set; }
    public string HaveYouAcceptedChrist { get; set; }
    public string HaveYouBeenWaterBaptised { get; set; }
    public string HaveYouBeenHolyGhostBaptised { get; set; }
    public string SalvationDate { get; set; }
    public string WaterBaptismDate { get; set; }
    public string HolyGhostBaptismDate { get; set; }
    public string DateOfFirstVisit { get; set; }
    public string PreviousChurch { get; set; }
    public string ContactPerson { get; set; }
    public string Comment { get; set; }
}

public partial class SavedReportQuery
{
    public System.Guid SavedReportQueriesID { get; set; }
    public string ReportName { get; set; }
    public string QueryString { get; set; }
    public System.DateTime ReportDate { get; set; }
    public string ReportOwner { get; set; }
    public string ReportCategory { get; set; }
}

public partial class Sermon
{
    public int SermonID { get; set; }
    public int MemberID { get; set; }
    public string SermonTitle { get; set; }
    public string Preacher { get; set; }
    public Nullable<System.DateTime> SermonDate { get; set; }
    public Nullable<decimal> Cost { get; set; }
    public Nullable<int> Quantity { get; set; }
    public Nullable<decimal> Discount { get; set; }
    public Nullable<decimal> SubTotal { get; set; }
}

public partial class SharingTable
{
    public int SharingTableID { get; set; }
    public int SharingMemberID { get; set; }
    public int SharedMemberID { get; set; }
    public int OccassionImageID { get; set; }
}

public partial class SpecialFund
{
    public int Id { get; set; }
    public int PledgeId { get; set; }
    public Nullable<System.DateTime> PayDate { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string PayMode { get; set; }
    public string PayReference { get; set; }
}

public partial class StandardReport
{
    public int Id { get; set; }
    public Nullable<int> BranchName { get; set; }
    public string Total { get; set; }
    public string MenTotal { get; set; }
    public string WomenTotal { get; set; }
    public string WaterBaptisedTotal { get; set; }
    public string HolySpiritBaptisedTotal { get; set; }
    public string Age35Total { get; set; }
    public string Children_0_to_12Total { get; set; }
    public string Teenage_13_to_19Total { get; set; }
    public string YoungAdult_20_to_35Total { get; set; }
    public string GhanaianMembership { get; set; }
    public string NoOfNationalsIndigenes { get; set; }
    public string NoOfOtherNationals { get; set; }
    public string Elders { get; set; }
    public string Deacons { get; set; }
    public string Deaconessess { get; set; }
    public string ChildrenDedicated { get; set; }
    public string AdultsSoulsWon { get; set; }
    public string OldMembersHolySpiritBaptised { get; set; }
    public string NewConvertsWaterBaptised { get; set; }
    public string NewConvertsHolySpiritBaptised { get; set; }
    public string TransferIn_0_to_19 { get; set; }
    public string TransferIn_19_to_Above { get; set; }
    public string TransferInTotal { get; set; }
    public string TransferOut_0_to_19 { get; set; }
    public string TransferOut_19_to_Above { get; set; }
    public string TransferOutTotal { get; set; }
    public string BackSliderWonBack { get; set; }
    public string BackSlidersBeingFollowed { get; set; }
    public string NumberOfHomeCells { get; set; }
    public string RalliesHeld { get; set; }
    public string AdultDeath { get; set; }
    public string Birth { get; set; }
    public string DeathAdultsAndChildren { get; set; }
    public string MarriagesBlessed { get; set; }
    public string ReportingPeriod { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> ReportYear { get; set; }
    public Nullable<int> CreatedBy { get; set; }
}

public partial class SuggestionBox
{
    public int SuggestionBoxID { get; set; }
    public int MemberID { get; set; }
    public System.DateTime CommentDate { get; set; }
    public string CommentCategory { get; set; }
    public string Comment { get; set; }
}

public partial class SupperUser
{
    public int SupperUserID { get; set; }
    public int SupperUserDetailsID { get; set; }
    public Nullable<System.DateTime> CreateOn { get; set; }
    public string CreateBy { get; set; }
}

public partial class SupperUserDetail
{
    public int SupperUserDetailsID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public Nullable<System.DateTime> DOB { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string Town { get; set; }
    public string PostZipCode { get; set; }
    public string Cournty { get; set; }
    public string Telephone { get; set; }
    public string Email { get; set; }
}

public partial class Support
{
    public int SupportID { get; set; }
    public Nullable<int> MemberID { get; set; }
    public string UserName { get; set; }
    public string ChurchName { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Subject { get; set; }
    public string Description { get; set; }
}

public partial class Table_Census
{
    public int Id { get; set; }
    public int BranchID { get; set; }
    public string AssemblyName { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string Surname { get; set; }
    public string MiddleName { get; set; }
    public string Telephone { get; set; }
    public string MobileNumber { get; set; }
    public string MaritalStatus { get; set; }
    public string ContactPerson { get; set; }
    public string Profession { get; set; }
    public string ActiveArea { get; set; }
    public string Occupation { get; set; }
    public string HasBornAgain { get; set; }
    public string DateBornAgain { get; set; }
    public string HasWaterBaptised { get; set; }
    public string DateWaterBaptised { get; set; }
    public string HasHolyGhostBaptised { get; set; }
    public string DateHolyGhostBaptised { get; set; }
    public string PreviousChurch { get; set; }
    public string DateFirstVisit { get; set; }
    public string ChurchContactPerson { get; set; }
    public string UrgentPrayerRequest { get; set; }
    public string PrayerRequestDetails { get; set; }
    public string CensusYear { get; set; }
    public string DateOfBirth { get; set; }
    public string Email { get; set; }
    public string AgeCategory { get; set; }
}

public partial class Table_WeeklyServiceReport
{
    public int Id { get; set; }
    public string SelectBranchName { get; set; }
    public string MenCount { get; set; }
    public string WomenCount { get; set; }
    public string ChildrenCount { get; set; }
    public string SermonSpeaker { get; set; }
    public string BibleStudyTopic { get; set; }
    public string KeyInformation { get; set; }
    public string MidWeek { get; set; }
    public string MissionaryOffering { get; set; }
    public string NewMembers { get; set; }
    public string Other { get; set; }
    public string SermonSummary { get; set; }
    public string SermonTitle { get; set; }
    public string Specify { get; set; }
    public string Tithes { get; set; }
    public string AbsentTwoWeeks { get; set; }
    public string ActivityDate { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string ServiceName { get; set; }
    public Nullable<int> SoulsWon { get; set; }
    public Nullable<int> HolySpiritBaptised { get; set; }
    public Nullable<int> WaterBaptised { get; set; }
    public Nullable<int> Visitation { get; set; }
}

public partial class TagTable
{
    public int TagTableID { get; set; }
    public int TaggingMemberID { get; set; }
    public int TaggedMemberID { get; set; }
    public int OccassionImageID { get; set; }
    public System.DateTime TaggingDate { get; set; }
}

public partial class Theme
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Path { get; set; }
}

public partial class Token
{
    public int Id { get; set; }
    public string Token1 { get; set; }
    public Nullable<System.DateTime> IssuedDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
}

public partial class Training
{
    public int TrainingID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime FromDate { get; set; }
    public System.DateTime ToDate { get; set; }
    public string TrainingType { get; set; }
    public string Location { get; set; }
    public string Purpose { get; set; }
    public string Attendees { get; set; }
}

public partial class Transfer
{
    public int BranchID { get; set; }
    public int MemberID { get; set; }
    public string TransferMode { get; set; }
    public string TransferType { get; set; }
    public string ToBranch { get; set; }
    public string FromBranch { get; set; }
    public string Status { get; set; }
    public Nullable<int> TransferDate { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
}

public partial class TransportEvent
{
    public int TransportEventID { get; set; }
    public string EventName { get; set; }
    public System.DateTime EventDate { get; set; }
    public string EventTime { get; set; }
    public string EventLocation { get; set; }
    public string EventDriver { get; set; }
    public string EventStatus { get; set; }
}

public partial class TransportEventBooking
{
    public int TransportEventBookingsID { get; set; }
    public int MemberID { get; set; }
    public int TransportEventID { get; set; }
    public string PickUpPoint { get; set; }
    public int NumberOfPersons { get; set; }
}

public partial class UKCity
{
    public int ID { get; set; }
    public string City { get; set; }
    public Nullable<bool> IsSelected { get; set; }
}

public partial class VendorApiKey
{
    public int Id { get; set; }
    public string VendorName { get; set; }
    public string Secret_Live { get; set; }
    public string Publishable_Live_Key { get; set; }
    public string Secret_Test { get; set; }
    public string Publishable_Test_Key { get; set; }
}

public partial class Visitation
{
    public int ID { get; set; }
    public int MemberID { get; set; }
    public string DateVisited { get; set; }
    public string VisitingOfficers { get; set; }
    public string Purpose { get; set; }
    public string Comment { get; set; }
    public string SupportAndDonation { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string CreatedOn { get; set; }
}

public partial class VW_Activities
{
    public int ActivityID { get; set; }
    public int Branch_ID { get; set; }
    public string Activity_Name { get; set; }
    public System.DateTime Created_ON { get; set; }
    public string Created_By { get; set; }
    public string Speaker { get; set; }
    public string Location { get; set; }
    public string Activity_Comment { get; set; }
}

public partial class VW_Association
{
    public string AssociationName { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
    public int AssociationId { get; set; }
}

public partial class VW_AttendanceReport
{
    public string ActivityName { get; set; }
    public System.DateTime AttendanceDate { get; set; }
    public int BranchID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string Telephone { get; set; }
    public string Gender { get; set; }
    public string Title { get; set; }
}

public partial class VW_BranchDetails
{
    public int BranchID { get; set; }
    public int ChurchDetailsID { get; set; }
    public string Name { get; set; }
    public string AddressOne { get; set; }
    public string AddressTwo { get; set; }
    public string PostZipCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Website { get; set; }
}

public partial class VW_ChurchDetails
{
    public string ChurchName { get; set; }
    public string CharityNumber { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string Town { get; set; }
    public string Telephone { get; set; }
    public string WebAddress { get; set; }
    public int ChurchID { get; set; }
    public string PostCode { get; set; }
}

public partial class VW_DeleteFinanceExpenditureItem
{
    public int ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string Source { get; set; }
}

public partial class VW_DeleteFinanceExpenditureSource
{
    public System.Guid ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Source { get; set; }
}

public partial class VW_DeleteFinanceIncomeItem
{
    public int ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string Source { get; set; }
}

public partial class VW_DeleteFinanceIncomeSource
{
    public System.Guid ID { get; set; }
    public System.DateTime Date { get; set; }
    public string Source { get; set; }
}

public partial class VW_DeleteFinancePayMode
{
    public int ID { get; set; }
    public string Alias { get; set; }
    public string PayMode { get; set; }
}

public partial class VW_GetAdminDetails
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public System.DateTime DOB { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string PostZipCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Permission { get; set; }
}

public partial class VW_GetExpenditureTransaction
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
    public decimal Amount { get; set; }
    public string ModeOfPayment { get; set; }
}

public partial class VW_GetFinanceExpenditureItem
{
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class VW_GetFinanceIncomeItem
{
    public string Name { get; set; }
    public string Description { get; set; }
}

public partial class VW_GetFinanceIncomeItemPayMode
{
    public string PayMode { get; set; }
}

public partial class VW_GetFinanceIncomeItemSource
{
    public string Source { get; set; }
}

public partial class VW_GetLinceInfo
{
    public int LicenseID { get; set; }
    public string LincenseNumber { get; set; }
    public System.DateTime LicenceStartDate { get; set; }
    public System.DateTime LicenceEndDate { get; set; }
    public int NumberOfUsers { get; set; }
}

public partial class VW_GetMemberDetails
{
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string DOB { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Comment { get; set; }
    public string Title { get; set; }
    public string PostCode { get; set; }
    public string Gender { get; set; }
    public string AgeCategory { get; set; }
    public string MembershipType { get; set; }
    public string RecordDate { get; set; }
}

public partial class VW_Groups
{
    public int ChurchGroupID { get; set; }
    public string Name { get; set; }
    public string Comment { get; set; }
    public string CreatedBy { get; set; }
    public System.DateTime DateCreated { get; set; }
    public string GroupType { get; set; }
}

public partial class VW_Profession
{
    public int ProfessionID { get; set; }
    public int MemberID { get; set; }
    public string ProfessionName { get; set; }
    public string CompanyName { get; set; }
    public string IsCurrentRole { get; set; }
}

public partial class GetDailyQuote_Result
{
    public Nullable<int> Id { get; set; }
    public string Book { get; set; }
    public string Chapter { get; set; }
    public string Verse { get; set; }
    public string Quote { get; set; }
}

public partial class GetToken_Result
{
    public int Id { get; set; }
    public string Token { get; set; }
    public Nullable<System.DateTime> IssuedDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
}

public partial class SP_AddMember_Result
{
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public Nullable<int> DistrictID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string DOB { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string PostCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Comment { get; set; }
    public byte[] Picture { get; set; }
    public string Gender { get; set; }
    public string AgeCategory { get; set; }
    public byte[] AgeCategoryRep { get; set; }
    public string MembershipType { get; set; }
    public string RecordDate { get; set; }
    public string Password { get; set; }
    public string LoginType { get; set; }
    public string MemberTracking { get; set; }
    public string MaritalStatus { get; set; }
    public string Nationality { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string Profession { get; set; }
    public string Ethnicity { get; set; }
    public Nullable<int> PasswordDate { get; set; }
    public string AssignedBranchGroups { get; set; }
    public string BranchGroupings { get; set; }
    public Nullable<int> ThemeID { get; set; }
}

public partial class Sp_Announcement_Result
{
    public int AnnouncementID { get; set; }
    public int BranchID { get; set; }
    public string AnnouncementType { get; set; }
    public string Sender { get; set; }
    public string Purpose { get; set; }
    public string Comment { get; set; }
}

public partial class sp_AttendanceHistory_Result
{
    public string ActivityName { get; set; }
    public string Date { get; set; }
    public Nullable<int> Count { get; set; }
}

public partial class sp_BranchBirthdays_Result
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Day { get; set; }
    public string Month { get; set; }
}

public partial class Sp_ChurchGroups_Result
{
    public int ChurchGroupID { get; set; }
    public string Name { get; set; }
    public System.DateTime DateCreated { get; set; }
    public string CreatedBy { get; set; }
    public string Comment { get; set; }
    public string GroupType { get; set; }
}

public partial class Sp_Communication_Result
{
    public int CommunicationID { get; set; }
    public int Member_ID { get; set; }
    public System.DateTime Communication_Date { get; set; }
    public string Communication_Type { get; set; }
    public string Communication_Purpose { get; set; }
    public string Communication_Outcome { get; set; }
}

public partial class SP_Contribution_Result
{
    public int ContributionID { get; set; }
    public int MemberID { get; set; }
    public string ContributionType { get; set; }
    public System.DateTime ContributionDate { get; set; }
    public decimal Amount { get; set; }
    public string Comment { get; set; }
}

public partial class SP_COVID_Attendance_Result
{
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public string Telephone { get; set; }
    public decimal Temperature { get; set; }
    public string ActivityName { get; set; }
    public System.DateTime AttendanceDate { get; set; }
    public string BranchName { get; set; }
}

public partial class Sp_Discipline_Result
{
    public int Discipline_ID { get; set; }
    public int Branch_ID { get; set; }
    public int Member_ID { get; set; }
    public string Member_Name { get; set; }
    public System.DateTime From_Date { get; set; }
    public System.DateTime End_Date { get; set; }
    public string Discipline_Type { get; set; }
    public string Comment { get; set; }
}

public partial class Sp_ExpenditureTransaction_Result
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime Date { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string Source { get; set; }
    public decimal Amount { get; set; }
    public string ModeOfPayment { get; set; }
}

public partial class sp_GetAppointmentHistory_Result
{
    public string Role { get; set; }
    public int StartDate { get; set; }
    public int EndDate { get; set; }
}

public partial class SP_GetContribution_Result
{
    public int ContributionID { get; set; }
    public int MemberID { get; set; }
    public string ContributionType { get; set; }
    public System.DateTime ContributionDate { get; set; }
    public decimal Amount { get; set; }
    public string Comment { get; set; }
}

public partial class sp_GivingHistory_Result
{
    public string Fund { get; set; }
    public string Date { get; set; }
    public Nullable<decimal> Amount { get; set; }
}

public partial class Sp_Leadership_Result
{
    public int Leadership_ID { get; set; }
    public string Title { get; set; }
    public System.DateTime Appointment_Date { get; set; }
    public System.DateTime Appointment_End_Date_ { get; set; }
    public string Leadership_Group { get; set; }
}

public partial class Sp_LeadershipChanges_Result
{
    public int ID { get; set; }
    public int BranchID { get; set; }
    public int MemberID { get; set; }
    public string Member_Name { get; set; }
    public string Old_Role { get; set; }
    public int OldBranchID { get; set; }
    public int NewBranchID { get; set; }
    public string Previous_Branch_Name { get; set; }
    public string New_Branch_Name { get; set; }
    public string New_Role { get; set; }
    public System.DateTime Appointment_Date { get; set; }
    public string Officiating_Minister { get; set; }
    public string Comment { get; set; }
}

public partial class Sp_Meeting_Result
{
    public int Meeting_ID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime Meeting_Date { get; set; }
    public string Meeting_Type { get; set; }
    public string Chair { get; set; }
    public string Purpose { get; set; }
    public string Comment { get; set; }
}

public partial class Sp_MemberGroup_Result
{
    public int Member_Group_ID { get; set; }
    public int Group_ID { get; set; }
    public string Group_Name { get; set; }
    public System.DateTime C_Date_Of_Joining { get; set; }
    public string Role_in_Group { get; set; }
}

public partial class SP_MemberImage_Result
{
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public Nullable<int> DistrictID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string DOB { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string PostCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Comment { get; set; }
    public byte[] Picture { get; set; }
    public string Gender { get; set; }
    public string AgeCategory { get; set; }
    public byte[] AgeCategoryRep { get; set; }
    public string MembershipType { get; set; }
    public string RecordDate { get; set; }
    public string Password { get; set; }
    public string LoginType { get; set; }
    public string MemberTracking { get; set; }
    public string MaritalStatus { get; set; }
    public string Nationality { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string Profession { get; set; }
    public string Ethnicity { get; set; }
    public Nullable<int> PasswordDate { get; set; }
    public string AssignedBranchGroups { get; set; }
    public string BranchGroupings { get; set; }
    public Nullable<int> ThemeID { get; set; }
}

public partial class Sp_MemberRelatives_Result
{
    public string RelationType { get; set; }
    public int MemberRelativeID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Gender { get; set; }
    public string EmailAddress { get; set; }
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public string Branch_Name { get; set; }
    public string Branch_Country { get; set; }
    public int RelationID { get; set; }
}

public partial class SP_Members_Result
{
    public int MemberID { get; set; }
    public int BranchID { get; set; }
    public Nullable<int> DistrictID { get; set; }
    public Nullable<int> AreaID { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string DOB { get; set; }
    public string AddressLineone { get; set; }
    public string Addresslinetwo { get; set; }
    public string PostCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string EmailAddress { get; set; }
    public string Comment { get; set; }
    public string Gender { get; set; }
    public string AgeCategory { get; set; }
    public string MembershipType { get; set; }
    public string RecordDate { get; set; }
    public string LoginType { get; set; }
    public string MaritalStatus { get; set; }
    public string Nationality { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string Profession { get; set; }
    public string Ethnicity { get; set; }
}

public partial class Sp_Profession_Result
{
    public int Profession_ID { get; set; }
    public string Profession_Name { get; set; }
    public string Company_Name { get; set; }
    public string Current_Role { get; set; }
}

public partial class Sp_SavedReportQueries_Result
{
    public System.Guid savedreportqueriesid { get; set; }
    public string ReportName { get; set; }
    public string QueryString { get; set; }
    public System.DateTime ReportDate { get; set; }
    public string ReportOwner { get; set; }
    public string ReportCategory { get; set; }
}

public partial class Sp_Training_Result
{
    public int TrainingID { get; set; }
    public int BranchID { get; set; }
    public System.DateTime FromDate { get; set; }
    public System.DateTime ToDate { get; set; }
    public string TrainingType { get; set; }
    public string Location { get; set; }
    public string Purpose { get; set; }
    public string Attendees { get; set; }
}

public partial class Sp_ValidateUserCredentials_Result
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public System.DateTime DOB { get; set; }
    public string AddressLineOne { get; set; }
    public string AddressLineTwo { get; set; }
    public string PostZipCode { get; set; }
    public string Town { get; set; }
    public string Country { get; set; }
    public string Telephone { get; set; }
    public string Email { get; set; }
    public string Permission { get; set; }
}

public partial class sp_WeeklyServiceAggregation_Result
{
    public string BranchName { get; set; }
    public string Month { get; set; }
    public string Year { get; set; }
    public string Tithes { get; set; }
    public string Other { get; set; }
    public string MissionaryOffering { get; set; }
    public string AbsentTwoWeeks { get; set; }
    public string ActivityDate { get; set; }
    public string BibleStudyTopic { get; set; }
    public Nullable<int> BranchID { get; set; }
    public string ChildrenCount { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<int> CreatedOn { get; set; }
    public Nullable<int> HolySpiritBaptised { get; set; }
    public string KeyInformation { get; set; }
    public string MenCount { get; set; }
    public string MidWeek { get; set; }
    public string SermonSpeaker { get; set; }
    public string SermonSummary { get; set; }
    public string SermonTitle { get; set; }
    public string ServiceName { get; set; }
    public Nullable<int> SoulsWon { get; set; }
    public string Specify { get; set; }
    public Nullable<int> Visitation { get; set; }
    public Nullable<int> WaterBaptised { get; set; }
    public string WomenCount { get; set; }
}

public partial class sp_WeeklyServiceStatistics_Result
{
    public string BranchName { get; set; }
    public string Month { get; set; }
    public string Year { get; set; }
    public Nullable<decimal> Tithes { get; set; }
    public Nullable<decimal> MissionaryOffering { get; set; }
    public Nullable<decimal> Other { get; set; }
    public Nullable<int> SoulsWon { get; set; }
    public Nullable<int> WaterBaptised { get; set; }
    public Nullable<int> ChildrenCount { get; set; }
    public Nullable<int> WomenCount { get; set; }
    public Nullable<int> MenCount { get; set; }
    public Nullable<int> Visitation { get; set; }
}

public partial class SplitInts_Result
{
    public Nullable<int> Item { get; set; }
}

public partial class usp_GetErrorInfo_Result
{
    public Nullable<int> ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}
